sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lprates/react-app-image -f Dockerfile.dev .

script:
  - docker run -e CI=true lprates/react-app-image npm run test
